#!/bin/bash

# Discover host directory mounted inside docker
LOCAL_VOLUME_MOUNT=$(cd $(dirname ${BASH_SOURCE[0]})/../ >/dev/null 2>&1 && pwd)
if [ ! -d "$LOCAL_VOLUME_MOUNT" ]; then
    echo "Invalid mount point: $LOCAL_VOLUME_MOUNT"
    echo "Usage:" $0 /path/to/local/volume/mount
    exit 1;
fi

# Discover linux source directory on this image
LINUX_DIR=${BUILD_BASE}/work/linux
if [ ! -d "$LINUX_DIR" ]; then
    echo "Linux source not found at: " ${BUILD_BASE}
fi

cd $LINUX_DIR
cp ${LOCAL_VOLUME_MOUNT}/cartesi-linux-config .config
make ARCH=riscv CROSS_COMPILE=riscv64-cartesi-linux-gnu- menuconfig
cp .config ${LOCAL_VOLUME_MOUNT}/cartesi-linux-config
